import { withTransaction } from '../db/postgres.mjs';
import { upsertInboundConversation,updateConversationLastMessage } from '../repositories/conversations.repository.mjs';
import { insertInboundMessage } from '../repositories/messages.repository.mjs';
import { upsertMediaMetadata } from '../repositories/media.repository.mjs';
import { markWebhookProcessed,markWebhookFailed } from '../repositories/webhook-events.repository.mjs';
import { addJob } from '../queues/queues.mjs';
import { publishRealtimeEvent } from '../realtime/pubsub.mjs';
const typeOf=(message)=>['image','audio','video','document','sticker'].find(type=>message?.[type])||message?.type||'text';
const bodyOf=(message,type)=>message?.text?.body||message?.[type]?.caption||message?.button?.text||message?.interactive?.button_reply?.title||'';
const routingValue=(prefix,phoneNumberId,fallback)=>process.env[`${prefix}_${String(phoneNumberId||'').replace(/\D/g,'')}`]||process.env[fallback]||null;
export const normalizeMetaPayload=(payload)=>{const out={messages:[],statuses:[]};for(const entry of payload?.entry||[])for(const change of entry?.changes||[]){const value=change?.value||{};const phoneNumberId=value.metadata?.phone_number_id||'';const names=new Map((value.contacts||[]).map(c=>[c.wa_id,c.profile?.name||'']));for(const m of value.messages||[]){const type=typeOf(m);const media=m[type]&&type!=='text'?m[type]:null;out.messages.push({providerMessageId:m.id,contactPhone:m.from,contactName:names.get(m.from)||'',phoneNumberId,queueId:routingValue('META_QUEUE',phoneNumberId,'CHAT_DEFAULT_QUEUE_ID'),serviceId:routingValue('META_SERVICE',phoneNumberId,'CHAT_DEFAULT_SERVICE_ID'),assignedAgentId:routingValue('META_ASSIGNED_AGENT',phoneNumberId,'CHAT_DEFAULT_ASSIGNED_AGENT_ID'),type,body:bodyOf(m,type),createdAt:new Date(Number(m.timestamp||Date.now()/1000)*1000).toISOString(),media:media?{providerMediaId:media.id,type,mimeType:media.mime_type}:null,raw:m});}for(const s of value.statuses||[])out.statuses.push({providerMessageId:s.id,status:s.status,raw:s});}return out;};
export const processInboundWebhook=async(data)=>{const normalized=normalizeMetaPayload(data.payload);try{for(const item of normalized.messages){const result=await withTransaction(async(client)=>{const conversation=await upsertInboundConversation(client,{...item,tenantId:data.tenantId});let media=null;if(item.media)media=await upsertMediaMetadata(client,{...item.media,tenantId:data.tenantId,conversationId:conversation.id});const message=await insertInboundMessage(client,{...item,tenantId:data.tenantId,conversationId:conversation.id,mediaId:media?.id});if(!message)return {duplicate:true,conversation};await updateConversationLastMessage(client,conversation.id,message);return {message,conversation,media};});if(result.message){if(result.media)await addJob('media','download-media',{tenantId:data.tenantId,mediaId:result.media.id,providerMediaId:result.media.provider_media_id},{jobId:`media:${data.tenantId}:${result.media.provider_media_id}`});const eventScope={tenantId:data.tenantId,conversationId:result.conversation.id,queueId:result.conversation.queue_id,assignedAgentId:result.conversation.assigned_agent_id,customerPhone:result.conversation.contact_phone};await publishRealtimeEvent({...eventScope,type:'new_message',data:{conversationId:result.conversation.id,message:result.message}});await publishRealtimeEvent({...eventScope,type:'conversation_updated',data:{conversationId:result.conversation.id,conversation:{...result.conversation,last_message:result.message.body,last_message_type:result.message.type,last_message_at:result.message.created_at,unread_count:Number(result.conversation.unread_count||0)+1}}});}}
  for(const status of normalized.statuses)await addJob('status','apply-status',{tenantId:data.tenantId,...status},{jobId:`status:${data.tenantId}:${status.providerMessageId}:${status.status}`});
  if(data.webhookEventId)await markWebhookProcessed(data.webhookEventId);return normalized;}catch(error){if(data.webhookEventId)await markWebhookFailed(data.webhookEventId,error).catch(()=>{});throw error;}};
